### ISSUE TITLE
String literal compared with variable 'm'. Did you intend to use strcmp() instead?

### ISSUE THREAD

**Issue by ghost** [ongakken/terminalInsanityCLI#38]
#### Occurred on:
+ **Commit**:  177ceb8a4a777eb961cdea8889065c74964d8a88
+ **File**:    [terminalInsanityCONSOLE/main.cpp](https://github.com/ongakken/terminalInsanityCLI/blob/177ceb8a4a777eb961cdea8889065c74964d8a88/terminalInsanityCONSOLE/main.cpp)
+ **LineNum**: [118](https://github.com/ongakken/terminalInsanityCLI/blob/177ceb8a4a777eb961cdea8889065c74964d8a88/terminalInsanityCONSOLE/main.cpp#L118)
+ **Code**:    `if(m == "")`

    
#### Currently on:
+ **Commit**:  4495e93be7beefdff67f0a643ebf69fce4a12016
+ **File**:    [terminalInsanityCONSOLE/main.cpp](https://github.com/ongakken/terminalInsanityCLI/blob/4495e93be7beefdff67f0a643ebf69fce4a12016/terminalInsanityCONSOLE/main.cpp)
+ **LineNum**: [118](https://github.com/ongakken/terminalInsanityCLI/blob/4495e93be7beefdff67f0a643ebf69fce4a12016/terminalInsanityCONSOLE/main.cpp#L118)

**Comment by danglingptr0x0** [comment]
the branch _lvl2_ fixes this issue. don't try to fix it again pls XD
